create table test.cars (id bigint generated by default as identity, color varchar(255), car_maker varchar(128), milleage integer, car_model varchar(255), car_year integer, primary key (id))
create table test.tech_ins (id bigint generated by default as identity, i_date date, report varchar(2048) not null, location varchar(128) not null, CAR_ID bigint, primary key (id))
alter table test.tech_ins add constraint FK_nh5b2yxwt1u9gxhgtpse8ecys foreign key (CAR_ID) references test.cars
