-- 2 +/- SELECT COUNT(*) FROM HOTEL.ADDRESS;  
INSERT INTO HOTEL.ADDRESS(ID, CITY, COUNTRY, ADDRESS_NUMBER, ZIP_CODE, STREET) VALUES
(1, 'Bucuresti', 'RO', 'yyy', 'zzz', 'xxx'),
(2, 'Bucuresti', 'Romania', '1X', '2Y', 'strada fara nume');    
-- 1 +/- SELECT COUNT(*) FROM HOTEL.CUSTOMER; 
INSERT INTO HOTEL.CUSTOMER(ID, LEGAL_ID, LEGAL_ID_TYPE, NAME, SEX, ADDRESS_ID) VALUES
(1, 'AX111', 'CI', 'ion', 'M', 1); 
-- 1 +/- SELECT COUNT(*) FROM HOTEL.HOTEL;    
INSERT INTO HOTEL.HOTEL(ID, NAME, RATING, ADDRESS_ID) VALUES
(38, 'Hotel A', 3, 2);          
-- 2 +/- SELECT COUNT(*) FROM HOTEL.ROOM;     
INSERT INTO HOTEL.ROOM(ID, FLOOR_NBR, ROOM_NBR, BED_NBR, AVAILABLE_FOR_RENT, HOTEL_ID) VALUES
(52, 1, '11', 2, TRUE, 38),
(53, 1, '12', 1, TRUE, 38); 
-- 1 +/- SELECT COUNT(*) FROM HOTEL.CUSTOMER_RECORD;          
INSERT INTO HOTEL.CUSTOMER_RECORD(ID, CUSTOMER_ID, ROOM_ID, CHECKED_IN, CHECKED_OUT) VALUES
(33, 1, 52, TIMESTAMP '2018-04-22 00:00:00', NULL);              
-- 4 +/- SELECT COUNT(*) FROM HOTEL.USER_ROLES;               
INSERT INTO HOTEL.USER_ROLES(USER_NAME, ROLE_NAME) VALUES
('pufi', 'receptioner'),
('fifi', 'receptioner'),
('fifi', 'manager_hotel'),
('me', 'xxxxx'); 
-- 3 +/- SELECT COUNT(*) FROM HOTEL.USERS;    
INSERT INTO HOTEL.USERS(USER_NAME, USER_PASS) VALUES
('pufi', 'gigi'),
('fifi', 'gigi'),
('me', 'me');   
