CREATE TABLE IF NOT EXISTS ADDRESS(ID SERIAL PRIMARY KEY,
  STREET VARCHAR(64),
  ADDRESS_NUMBER VARCHAR(12),
  CITY VARCHAR(64),
  COUNTRY VARCHAR(64) NOT NULL,
  ZIP_CODE VARCHAR(12));
CREATE TABLE IF NOT EXISTS CUSTOMER(ID SERIAL PRIMARY KEY,
  NAME VARCHAR(128),
  SEX CHAR(1), -- M/F
  LEGAL_ID VARCHAR(32),
  LEGAL_ID_TYPE VARCHAR(32),
  ADDRESS_ID INTEGER , FOREIGN KEY (ADDRESS_ID) REFERENCES HOTEL.ADDRESS(ID));
--DROP TABLE ROOM;
CREATE TABLE IF NOT EXISTS HOTEL(ID SERIAL PRIMARY KEY,
  NAME VARCHAR(128),
  RATING TINYINT,
  ADDRESS_ID INTEGER,
  FOREIGN KEY (ADDRESS_ID) REFERENCES HOTEL.ADDRESS(ID));
CREATE TABLE IF NOT EXISTS  ROOM(ID SERIAL PRIMARY KEY,
  FLOOR_NBR TINYINT,
  ROOM_NBR VARCHAR(32),
  BED_NBR TINYINT,
  AVAILABLE_FOR_RENT BOOLEAN,
  HOTEL_ID INTEGER,  FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL.HOTEL(ID));
CREATE TABLE IF NOT EXISTS CUSTOMER_RECORD(ID SERIAL PRIMARY KEY,
  CUSTOMER_ID INTEGER,
  ROOM_ID INTEGER,
  CHECKED_IN TIMESTAMP NOT NULL,
  CHECKED_OUT TIMESTAMP,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES HOTEL.CUSTOMER(ID),
    FOREIGN KEY (ROOM_ID) REFERENCES HOTEL.ROOM(ID)

);

CREATE TABLE HOTEL.USERS (
	USER_NAME VARCHAR(15) NOT NULL,
	USER_PASS VARCHAR(15) NOT NULL,
	CONSTRAINT CONSTRAINT_4D PRIMARY KEY (USER_NAME)
) ;
CREATE UNIQUE INDEX PRIMARY_KEY_4D ON HOTEL.USERS (USER_NAME) ;

CREATE TABLE HOTEL.USER_ROLES (
	USER_NAME VARCHAR(15) NOT NULL,
	ROLE_NAME VARCHAR(15) NOT NULL,
	CONSTRAINT CONSTRAINT_C PRIMARY KEY (USER_NAME,ROLE_NAME)
) ;
CREATE UNIQUE INDEX PRIMARY_KEY_C ON HOTEL.USER_ROLES (USER_NAME,ROLE_NAME) ;


 